= Privacy
:page-layout: privacy
:page-exclude: true

We use Piwik PRO Analytics Suite as our website/app analytics software and consent management tool.
We collect data about website visitors based on https://help.piwik.pro/support/getting-started/cookies-created-by-piwik-pro/[cookies].
The collected information may include a visitor's IP address, operating system, browser ID, browsing activity and other information.
See the https://help.piwik.pro/support/getting-started/what-data-does-piwik-pro-collect/[scope of data collected by Piwik PRO].

We calculate metrics like bounce rate, page views, sessions and the like to understand how our website/app is used.
We may also create visitors' profiles based on browsing history to analyze visitor behavior, show personalized content and run online campaigns.

We host our solution on Microsoft Azure in Germany/Netherlands/United States/Hong Kong/ElastX in Sweden, and the data is stored for 14/25 months.

The purpose of data processing: analytics and conversion tracking based on consent.
Legal basis: Art. 6 (1)(a) GDPR.

Piwik PRO does not send the data about you to any other sub-processors or third parties and does not use it for its own purposes.
For more, read https://piwik.pro/privacy-policy/?pk_vid=2f6011d13b3288ba1667283552dcc0da#product[Piwik PRO's privacy policy].

