= The Dangers of DHMO, ACT NOW!
:page-layout: post
:datetime: 2005-09-07 18:18
:page-tags: [humor]

NOTE: Imported from previous blog.

Usually, I'm quite liberal about stuff like this, but I must draw a line somewhere.
There exists a chemical substance called http://www.dhmo.org/[DHMO],
or Dihydrogen Monoxide, that is one of the most deadly substances on the planet.

DHMO is a color-, taste- and odorless liquid that is responsible for the deaths of several thousands every year.
Last year alone, over one hundred thousand persons died from the direct or indirect effects of DHMO.
DHMO, also known as hydric acid is a major part in acid rain, it can in both liquid and gaseous form cause severe burns. DHMO is added to several sorts of junk-food, and in its two forms deuterium hydromonoxide and dideuterium monoxide it is a vital component for the creation of thermonuclear bombs.

It is a vile substance, that unfortunately can be found almost everywhere.
If you have a child in school, the probability that he or she consumes DHMO-contaminated milk for lunch is almost 100%.
Do you really want to have your children exposed to DHMO?

Please, write your MEP or MP so that they are made aware of this horrible substance and can take the proper steps towards the ban of DHMO.

== Hall of fame Comments

[quote,Anonymous,2006-02-07 02:55]
You're dumb.
We can not ban DHMO! It's water!
Of course milk ahs water in it.
It is not a contaminant, it is a source of life.
