= Star Trek Influences
Mattias Holm
:lang: en
:page-layout: post
:datetime: 2006-12-02 20:48
:page-tags: [science]
:page-category: science

[.lead]
A commentary about the influence Star Trek had on the world.

Holm's blog, stardate 60386.5

Some time ago I watched a show on the discovery channel that actually got me thinking quite a bit.
The programme was about how https://startrek.com[Star Trek]
had https://www.imdb.com/title/tt0814142/[changed the world].
The show was led by none other than William Shatner,
captain of the USS Enterprise in the original series.

I did watch Star Trek when I was younger,
the reason for this was my already big interest in space and astronomy.
I never really realized until now what influence the show has had on me.
Take for example my federalistic stance in politics,
I am now pretty sure that this comes from me watching Star Trek,
seeing the https://en.wikipedia.org/wiki/United_Federation_of_Planets[United Federation of Planets]
at works in a fairly optimistic view of the world.
Star Trek is also a show preaching the wonders of technology
(this is what the Discovery programme focused on),
and this is something that has definitely shaped my life.

It should come as no surprise for those that know me
that my stance is basically that the solution for most of the problems
that we are facing in the world today lies in technology.
Technology is in-fact the ultimate solution and salvation.

Technologies that have been directly inspired by the series are for example the mobile phone,
https://en.wikipedia.org/wiki/QuickTime[QuickTime]
and the https://en.wikipedia.org/wiki/Jet_injector[jet injector] (known as the hypospray in Star Trek).
There are several more examples of Star Trek inspired technology
that exists today or is under development.

Now the only thing I am missing is those lovely warp drive engines.
I refuse to believe people who say it cannot be done.
Lets hope for _new physics_(TM).

Live long and prosper!
